In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
from sklearn.metrics import mean_squared_error, r2_score
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import random
import warnings
np.random.seed(34)
warnings.filterwarnings('ignore')

In [3]:
data=pd.read_csv('D:/bachelor semester/datasets/turbo_fans_with_RUL.csv')
test=pd.read_csv('D:/bachelor semester/TURBO FAN/test_data.csv')
dfrul = pd.read_csv('D:/bachelor semester/TURBO FAN/RUL_FD001.txt',header=None,index_col=False,names=['RUL'])

In [4]:
from sklearn.model_selection import train_test_split
drop_labels = ['unit_number','time_cycles','setting_1','setting_2','setting_3']
train=data.drop(drop_labels,axis=1)
rul=data['RUL']
x_train, x_test, y_train, y_test=train_test_split(train,rul, test_size=0.3, random_state=42)

print('x_train:', x_train.shape, '... ', 'y_train:', y_train.shape, '... ', 'x_test:', x_test.shape, '... ', 'y_test:', y_test.shape)

x_train: (14441, 22) ...  y_train: (14441,) ...  x_test: (6190, 22) ...  y_test: (6190,)

In [5]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
#Droping the target variable
x_train.drop(columns=['RUL'], inplace=True)
x_test.drop(columns=['RUL'], inplace=True)
#Scaling X_train and X_test
x_train_scale=scaler.fit_transform(x_train)
x_test_scale=scaler.transform(x_test)

print(x_test_scale.shape)

(6190, 21)

In [6]:
#linear regression
from sklearn.linear_model import LinearRegression
modellr=LinearRegression()

#svr
from sklearn.svm import SVR
regressor = SVR(kernel='rbf')

#random_forest
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(max_features="sqrt", random_state=42)

In [7]:
#evaluating functions
#R2 score & RMSE & MAER
def evaluate(y_true, y_hat, label='test'):
    mse = mean_squared_error(y_true, y_hat)
    rmse = np.sqrt(mse)
    variance = r2_score(y_true, y_hat)
    print('{} set RMSE:{}, R2:{}'.format(label, rmse, variance))


#plot real data and the predicted one to make some comparison
def plot_predActual(y_test, y_test_hat):
  
    indices = np.arange(len(y_test_hat))
    wth= 0.6
    plt.figure(figsize=(70,30))
    true_values = [int(x) for x in y_test.values]
    predicted_values = list(y_test_hat)

    plt.bar(indices, true_values, width=wth,color='b', label='True RUL')
    plt.bar([i for i in indices], predicted_values, width=0.5*wth, color='r', alpha=0.7, label='Predicted RUL')

    plt.legend(prop={'size': 40})
    plt.tick_params(labelsize=40)

    plt.show()

In [8]:
#linear regression
#training the emodel
modellr.fit(x_train_scale,y_train) #Fitting 

y_lr_train = modellr.predict(x_train_scale) #Prediction on train data
evaluate(y_train,y_lr_train, label='train')

y_lr_test = modellr.predict(x_test_scale)  #Prediction on test data
evaluate(y_test, y_lr_test, label='test')


input_values = (518.67,642.56,1582.96,1400.97,14.62,21.61,553.85,2388,9040.8,1.3,47.24,522.47,2388.03,8131.07,8.4076,0.03,391,2388,100,38.97,23.3106)
#184
# Convert input values to a NumPy array
input_arr = np.asarray(input_values)

# Reshape the array to match the expected input shape of the model
input_reshaped = input_arr.reshape(1, -1)  # Reshape to (1, 11)

scaled_array = scaler.transform(input_reshaped)

# Make the prediction
prediction = modellr.predict(scaled_array)
prediction

train set RMSE:44.7994102333131, R2:0.583093872579288
test set RMSE:44.386478219983914, R2:0.5698693780582695

array([170.53668213])

In [9]:
#SVR
regressor.fit(x_train_scale, y_train) # fitting

y_svr_train = regressor.predict(x_train_scale) #Prediction on train data
evaluate(y_train,y_svr_train, label='train')

y_svr_test = regressor.predict(x_test_scale) #Prediction on test data
evaluate(y_test, y_svr_test, label='test')

input_values = (518.67,642.56,1582.96,1400.97,14.62,21.61,553.85,2388,9040.8,1.3,47.24,522.47,2388.03,8131.07,8.4076,0.03,391,2388,100,38.97,23.3106)
#184
# Convert input values to a NumPy array
input_arr = np.asarray(input_values)

# Reshape the array to match the expected input shape of the model
input_reshaped = input_arr.reshape(1, -1)  # Reshape to (1, 11)

scaled_array = scaler.transform(input_reshaped)

# Make the prediction
prediction = regressor.predict(scaled_array)
prediction

train set RMSE:43.56448464126648, R2:0.605761670162996
test set RMSE:43.25328799173457, R2:0.5915515616464357

array([170.35194436])

In [10]:
#Random forest regressor
rf.fit(x_train_scale, y_train)
# predict and evaluate
y_rf_train = rf.predict(x_train_scale)
evaluate(y_train,y_rf_train, label='train')

y_rf_test = rf.predict(x_test_scale)
evaluate(y_test, y_rf_test, label='test')

input_values = (518.67,642.56,1582.96,1400.97,14.62,21.61,553.85,2388,9040.8,1.3,47.24,522.47,2388.03,8131.07,8.4076,0.03,391,2388,100,38.97,23.3106)
#184
# Convert input values to a NumPy array
input_arr = np.asarray(input_values)

# Reshape the array to match the expected input shape of the model
input_reshaped = input_arr.reshape(1, -1)  # Reshape to (1, 11)


scaled_array = scaler.transform(input_reshaped)

# Make the prediction
prediction = rf.predict(scaled_array)
prediction

train set RMSE:15.408303170220156, R2:0.9506822432050425
test set RMSE:41.294428580147525, R2:0.6277095396793031

array([185.79])

In [15]:
#dropping un  necessary columns

In [11]:
#drop unecessary coulumns
drop_labels2=['s_1', 's_5','s_6','s_10',  's_16', 's_18', 's_19']
x_train_2=x_train.drop(columns=drop_labels2, axis=1) # drop the constant columns from the train dataset
x_test_2=x_test.drop(columns=drop_labels2, axis=1)  # drop the constant columns from the test dataset
x_train_2_scale=scaler.fit_transform(x_train_2) #scaling X_train_2
x_test_2_scale=scaler.fit_transform(x_test_2) #scaling X_test_2
y_train_clip=y_train.clip(upper=195)  #Clipping y_train to have 195 as the maximum value

In [12]:
#linear regression
modellr.fit(x_train_2_scale,y_train_clip)

y_lr_train = modellr.predict(x_train_2_scale)
evaluate(y_train_clip,y_lr_train, label='train')

y_lr_test = modellr.predict(x_test_2_scale)
evaluate(y_test, y_lr_test, label='test')

input_values = (642.15,1578.73,1399.13,554.7,2388.04,9057.22,47.31,522.14,2388.07,8139.57,8.4075,391,39.07,23.3474)
#131
# Convert input values to a NumPy array
input_arr = np.asarray(input_values)

# Reshape the array to match the expected input shape of the model
input_reshaped = input_arr.reshape(1, -1)  # Reshape to (1, 11)

scaled_array = scaler.transform(input_reshaped)

# Make the prediction
prediction = modellr.predict(scaled_array)
prediction

train set RMSE:35.92640871080577, R2:0.6502716889521982
test set RMSE:46.87318851003082, R2:0.5203240103333368

array([156.00516031])

In [13]:
#svr 
regressor.fit(x_train_2_scale, y_train)

y_svr_train = regressor.predict(x_train_2_scale)
evaluate(y_train_clip,y_svr_train, label='train')

y_svr_test = regressor.predict(x_test_2_scale)
evaluate(y_test, y_svr_test, label='test')


input_values = (642.15,1578.73,1399.13,554.7,2388.04,9057.22,47.31,522.14,2388.07,8139.57,8.4075,391,39.07,23.3474)
#131
# Convert input values to a NumPy array
input_arr = np.asarray(input_values)

# Reshape the array to match the expected input shape of the model
input_reshaped = input_arr.reshape(1, -1)  # Reshape to (1, 11)

scaled_array = scaler.transform(input_reshaped)
# Make the prediction
prediction = regressor.predict(scaled_array)
prediction

train set RMSE:32.91543148706822, R2:0.7064363470171213
test set RMSE:48.75516379159361, R2:0.48103242301470384

array([151.19533681])

In [14]:
#random forest regression
model=rf.fit(x_train_2_scale, y_train_clip)
# predict and evaluate
y_rf_train = rf.predict(x_train_2_scale)
evaluate(y_train_clip,y_rf_train, label='train')

y_rf_test = rf.predict(x_test_2_scale)
evaluate(y_test, y_rf_test, label='test')


input_values = (642.15,1578.73,1399.13,554.7,2388.04,9057.22,47.31,522.14,2388.07,8139.57,8.4075,391,39.07,23.3474)
#131
# Convert input values to a NumPy array
input_arr = np.asarray(input_values)

# Reshape the array to match the expected input shape of the model
input_reshaped = input_arr.reshape(1, -1)  # Reshape to (1, 11)

scaled_array = scaler.transform(input_reshaped)

# Make the prediction
prediction = rf.predict(scaled_array)
prediction

train set RMSE:12.036862499525814, R2:0.9607418547981479
test set RMSE:45.81838291793876, R2:0.5416697719315231

array([137.34])

In [15]:
# trying xgboost alghorithm 
import xgboost
xgb = xgboost.XGBRegressor(n_estimators=110, learning_rate=0.02, gamma=0, subsample=0.8,colsample_bytree=0.5, max_depth=3)
xgb.fit(x_train_2_scale, y_train_clip)


y_xgb_train = xgb.predict(x_train_2_scale)
evaluate(y_train_clip,y_xgb_train, label='train')

y_xgb_test = xgb.predict(x_test_2_scale)
evaluate(y_test, y_xgb_test, label='test')


input_values = (642.15,1578.73,1399.13,554.7,2388.04,9057.22,47.31,522.14,2388.07,8139.57,8.4075,391,39.07,23.3474)
#131
# Convert input values to a NumPy array
input_arr = np.asarray(input_values)

# Reshape the array to match the expected input shape of the model
input_reshaped = input_arr.reshape(1, -1)  # Reshape to (1, 11)

scaled_array = scaler.transform(input_reshaped)

# Make the prediction
prediction = xgb.predict(scaled_array)
prediction

train set RMSE:33.91737789695452, R2:0.6882921652069747
test set RMSE:45.48576025203659, R2:0.5483001960847009

array([143.02803], dtype=float32)

In [21]:
#drop unnicessary columns and use historical data

In [16]:
#In this section we are trying to discover a time series pattern in our features 
#as we add to our data a new feature called 'rolling mean feature'. 
#It's a equivalent to the mean value of a feature considering 10 time cycles.
#It will be computed for every feature.

df=data.copy()
for x in x_train_2.columns:
    df[x+'_rm']=0
print(df.columns)

drop_labels2=['s_1', 's_5','s_6','s_10','s_16', 's_18', 's_19']
df=df.drop(columns=['setting_1','setting_2','setting_3']+drop_labels2+['RUL'], axis=1)
X_valid_3=test.drop(columns=['unit_number','time_cycles']+['setting_1','setting_2','setting_3']+drop_labels2, axis=1)

df

Index(['unit_number', 'time_cycles', 'setting_1', 'setting_2', 'setting_3',
       's_1', 's_2', 's_3', 's_4', 's_5', 's_6', 's_7', 's_8', 's_9', 's_10',
       's_11', 's_12', 's_13', 's_14', 's_15', 's_16', 's_17', 's_18', 's_19',
       's_20', 's_21', 'RUL', 's_2_rm', 's_3_rm', 's_4_rm', 's_7_rm', 's_8_rm',
       's_9_rm', 's_11_rm', 's_12_rm', 's_13_rm', 's_14_rm', 's_15_rm',
       's_17_rm', 's_20_rm', 's_21_rm'],
      dtype='object')

,unit_number,time_cycles,s_2,s_3,s_4,s_7,s_8,s_9,s_11,s_12,...,s_8_rm,s_9_rm,s_11_rm,s_12_rm,s_13_rm,s_14_rm,s_15_rm,s_17_rm,s_20_rm,s_21_rm
0,1,1,641.82,1589.70,1400.60,554.36,2388.06,9046.19,47.47,521.66,...,0,0,0,0,0,0,0,0,0,0
1,1,2,642.15,1591.82,1403.14,553.75,2388.04,9044.07,47.49,522.28,...,0,0,0,0,0,0,0,0,0,0
2,1,3,642.35,1587.99,1404.20,554.26,2388.08,9052.94,47.27,522.42,...,0,0,0,0,0,0,0,0,0,0
3,1,4,642.35,1582.79,1401.87,554.45,2388.11,9049.48,47.13,522.86,...,0,0,0,0,0,0,0,0,0,0
4,1,5,642.37,1582.85,1406.22,554.00,2388.06,9055.15,47.28,522.19,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20626,100,196,643.49,1597.98,1428.63,551.43,2388.19,9065.52,48.07,519.49,...,0,0,0,0,0,0,0,0,0,0
20627,100,197,643.54,1604.50,1433.58,550.86,2388.23,9065.11,48.04,519.68,...,0,0,0,0,0,0,0,0,0,0
20628,100,198,643.42,1602.46,1428.18,550.94,2388.24,9065.90,48.09,520.01,...,0,0,0,0,0,0,0,0,0,0
20629,100,199,643.23,1605.26,1426.53,550.68,2388.25,9073.72,48.39,519.67,...,0,0,0,0,0,0,0,0,0,0
20630,100,200,643.85,1600.38,1432.14,550.79,2388.26,9061.48,48.20,519.30,...,0,0,0,0,0,0,0,0,0,0

In [17]:
#dealing with last line problem
def update_rolling_mean(data, mask):
    for x, group in mask.groupby("unit_number"):
        for x in x_train_2.columns:
            data.loc[group.index[10:], x+"_rm"] = data.loc[group.index, x].rolling(10).mean()[10:]
            data.loc[group.index[:10], x+"_rm"] = data.loc[group.index[:10], x]

update_rolling_mean(df, df)
update_rolling_mean(X_valid_3, test)

X_valid_3=X_valid_3.fillna(0)

#saving the modified dataset
df.iloc[-1,-14:]=df.iloc[-2,-14:]
X_valid_3.iloc[-1,-14:]=X_valid_3.iloc[-2,-14:]

In [18]:
train_tm=df
train_tm.head()

,unit_number,time_cycles,s_2,s_3,s_4,s_7,s_8,s_9,s_11,s_12,...,s_8_rm,s_9_rm,s_11_rm,s_12_rm,s_13_rm,s_14_rm,s_15_rm,s_17_rm,s_20_rm,s_21_rm
0,1,1,641.82,1589.70,1400.60,554.36,2388.06,9046.19,47.47,521.66,...,2388.06,9046.19,47.47,521.66,2388.02,8138.62,8.4195,392.0,39.06,23.4190
1,1,2,642.15,1591.82,1403.14,553.75,2388.04,9044.07,47.49,522.28,...,2388.04,9044.07,47.49,522.28,2388.07,8131.49,8.4318,392.0,39.00,23.4236
2,1,3,642.35,1587.99,1404.20,554.26,2388.08,9052.94,47.27,522.42,...,2388.08,9052.94,47.27,522.42,2388.03,8133.23,8.4178,390.0,38.95,23.3442
3,1,4,642.35,1582.79,1401.87,554.45,2388.11,9049.48,47.13,522.86,...,2388.11,9049.48,47.13,522.86,2388.08,8133.83,8.3682,392.0,38.88,23.3739
4,1,5,642.37,1582.85,1406.22,554.00,2388.06,9055.15,47.28,522.19,...,2388.06,9055.15,47.28,522.19,2388.04,8133.80,8.4294,393.0,38.90,23.4044

In [19]:
#3rd attempt (Data without useless sensors, with historical data
train_tm=train_tm.drop(['unit_number','time_cycles'], axis=1)
X_train_tm, X_test_tm, y_train_tm, y_test_tm=train_test_split(train_tm,train['RUL'].clip(upper=195), test_size=0.35, random_state=42)
X_train_tm_s=scaler.fit_transform(X_train_tm)
X_test_tm_s=scaler.fit_transform(X_test_tm)
X_val3=pd.concat([test['unit_number'],X_valid_3],axis=1)
X_valid3 = X_val3.groupby('unit_number').last().reset_index().drop(columns=['unit_number'])
X_valid_s=scaler.fit_transform(X_valid3)

In [20]:
#linear regression 
modellr.fit(X_train_tm_s, y_train_tm)

y_lr_train = modellr.predict(X_train_tm_s)
evaluate(y_train_tm,y_lr_train, label='train')

y_lr_test = modellr.predict(X_test_tm_s)
evaluate(y_test_tm, y_lr_test, label='test')


input_values = (642.15,1578.73,1399.13,554.7,2388.04,9057.22,47.31,522.14,2388.07,8139.57,8.4075,391,39.07,23.3474,
                642.311,1586.558,1399.762,554.074,2388.036,9055.928,47.289,522.099,2388.048,8138.996000000001,8.408919999999998,391.5,38.938,23.363899999999997)
#131
# Convert input values to a NumPy array
input_arr = np.asarray(input_values)

# Reshape the array to match the expected input shape of the model
input_reshaped = input_arr.reshape(1, -1)  # Reshape to (1, 11)

scaled_array = scaler.transform(input_reshaped)

# Make the prediction
prediction = modellr.predict(scaled_array)
prediction

train set RMSE:35.42192097028067, R2:0.6597022455059893
test set RMSE:36.20656087389736, R2:0.6368175454792206

array([198.38359236])

In [21]:
#svr algorithm
regressor.fit(X_train_tm_s, y_train_tm)

y_svr_train = regressor.predict(X_train_tm_s)
evaluate(y_train_tm,y_svr_train, label='train')

y_svr_test = regressor.predict(X_test_tm_s)
evaluate(y_test_tm, y_svr_test, label='test')


input_values = (642.15,1578.73,1399.13,554.7,2388.04,9057.22,47.31,522.14,2388.07,8139.57,8.4075,391,39.07,23.3474,
                642.311,1586.558,1399.762,554.074,2388.036,9055.928,47.289,522.099,2388.048,8138.996000000001,8.408919999999998,391.5,38.938,23.363899999999997)
#131
# Convert input values to a NumPy array
input_arr = np.asarray(input_values)

# Reshape the array to match the expected input shape of the model
input_reshaped = input_arr.reshape(1, -1)  # Reshape to (1, 11)

scaled_array = scaler.transform(input_reshaped)

# Make the prediction
prediction = regressor.predict(scaled_array)
prediction

train set RMSE:32.48452364307428, R2:0.7138011601047023
test set RMSE:33.82872041899003, R2:0.6829546036019843

array([166.71505156])

In [22]:
#Random forest regression
rf = RandomForestRegressor(max_features="sqrt", random_state=42)
rf.fit(X_train_tm_s, y_train_tm)
# predict and evaluate
y_hat_train = rf.predict(X_train_tm_s)
evaluate(y_train_tm,y_hat_train, label='train')
y_hat_test = rf.predict(X_test_tm_s)
evaluate(y_test_tm, y_hat_test, label='test')


input_values = (642.15,1578.73,1399.13,554.7,2388.04,9057.22,47.31,522.14,2388.07,8139.57,8.4075,391,39.07,23.3474,
                642.311,1586.558,1399.762,554.074,2388.036,9055.928,47.289,522.099,2388.048,8138.996000000001,8.408919999999998,391.5,38.938,23.363899999999997)
#131
# Convert input values to a NumPy array
input_arr = np.asarray(input_values)

# Reshape the array to match the expected input shape of the model
input_reshaped = input_arr.reshape(1, -1)  # Reshape to (1, 11)

scaled_array = scaler.transform(input_reshaped)

# Make the prediction
prediction = rf.predict(scaled_array)
prediction

train set RMSE:9.787255139684294, R2:0.9740201473464815
test set RMSE:29.95828541820653, R2:0.7513524307207359

array([182.9])

In [23]:
# Params found using Bayesian Optimisation
xgb = xgboost.XGBRegressor(n_estimators=50, 
                           max_depth=6,
                           learning_rate=0.1,
                           reg_lambda=0.02,
                           gamma=0.4,
                           random_state=42)
xgb.fit(X_train_tm_s, y_train_tm)

# predict and evaluate
y_hat_train = xgb.predict(X_train_tm_s)
evaluate(y_train_tm, y_hat_train, 'train')

y_hat_test = xgb.predict(X_test_tm_s)
evaluate(y_test_tm, y_hat_test)


input_values = (642.15,1578.73,1399.13,554.7,2388.04,9057.22,47.31,522.14,2388.07,8139.57,8.4075,391,39.07,23.3474,
                642.311,1586.558,1399.762,554.074,2388.036,9055.928,47.289,522.099,2388.048,8138.996000000001,8.408919999999998,391.5,38.938,23.363899999999997)
#131
# Convert input values to a NumPy array
input_arr = np.asarray(input_values)

# Reshape the array to match the expected input shape of the model
input_reshaped = input_arr.reshape(1, -1)  # Reshape to (1, 11)

scaled_array = scaler.transform(input_reshaped)

# Make the prediction
prediction = xgb.predict(scaled_array)
prediction

train set RMSE:24.44225850465359, R2:0.8379692173705675
test set RMSE:30.450946292934663, R2:0.7431072212034071

array([183.9188], dtype=float32)